name: Docker Image Builds

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '30 */12 * * *'
  push:
  pull_request:
    branches: [ "main" ]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME_PREFIX: ${{ github.repository }}

permissions:
  contents: read
  packages: write
  # This is used to complete the identity challenge with sigstore/fulcio when
  # running outside of PRs.
  id-token: write
  # https://github.com/actions/attest-build-provenance
  attestations: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: treat lint errors as warnings on GitLab CI side
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          recursive: true
          trusted-registries: quay.io, ghcr.io,docker.io,dock.mau.dev
        continue-on-error: true

  mkdocs-material:
    name: Custom image on Material for Mkdocs
    runs-on: ubuntu-latest
    needs: [ lint ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Log into RHQCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.RHQCR_BOT_USERNAME }}
          password: ${{ secrets.RHQCR_BOT_TOKEN }}
      - name: Login into GLCR on mau.dev
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: dock.mau.dev
          username: ${{ secrets.GLCR_MAUDEV_DEPLOY_USERNAME }}
          password: ${{ secrets.GLCR_MAUDEV_DEPLOY_TOKEN }}
      
      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME_PREFIX }}/mkdocs-material
            dock.mau.dev/${{ env.IMAGE_NAME_PREFIX }}/mkdocs-material
            quay.io/ajhalili2006/mkdocs-material-build-ci
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,enable=true,priority=100,prefix=commit-,suffix=,format=long
            type=schedule,pattern=nightly
            type=schedule,prefix=nightly-,pattern={{date 'YYYYMMDDhhmmss'}}
            type=raw,prefix=branch-,value={{branch}}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: "Build and push Docker image [nightly builds]"
        if: github.event_name == 'schedule'
        id: nightly-build
        uses: docker/build-push-action@v4.1.1
        with:
          context: docker/mkdocs-material
          #file: Dockerfile
          # workaround: https://github.com/moby/buildkit/issues/2713#issuecomment-1068540101
          push: true
          #load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=buildkit-mkdocs-material
          cache-to: type=gha,mode=max,scope=buildkit-mkdocs-material
      
      - name: Build and push Docker image
        if: github.event_name != 'schedule'
        id: build
        uses: docker/build-push-action@v4.1.1
        with:
          context: docker/mkdocs-material
          #file: Dockerfile
          # workaround: https://github.com/moby/buildkit/issues/2713#issuecomment-1068540101
          push: ${{ github.event_name != 'pull_request' }}
          #load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-to: type=gha,mode=max,scope=buildkit-mkdocs-material

      # First, we sign our images with cosign first...
      - name: "Sign the published Docker image with cosign [nightly builds]"
        if: ${{ github.event_name == 'schedule' }}
        id: cosign-nightly-builds
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.nightly-build.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Sign the published Docker image with cosign
        if: ${{ github.event_name == 'push' }}
        id: cosign
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
        continue-on-error: true

      # ...and then generate a build attestation via actions/attest-build-provenance workflow.
      - name: "Generate attestation for GitHub API access [nightly builds]"
        uses: actions/attest-build-provenance@v1
        if: ${{ github.event_name == 'schedule' }}
        id: attest-nightly-builds
        with:
          subject-name: ghcr.io/${{ env.IMAGE_NAME_PREFIX }}/mkdocs-material
          subject-digest: ${{ steps.nightly-build.outputs.digest }}
          push-to-registry: true
      - name: Generate attestation for GitHub API access
        uses: actions/attest-build-provenance@v1
        if: ${{ github.event_name == 'push' }}
        id: attest
        with:
          subject-name: ghcr.io/${{ env.IMAGE_NAME_PREFIX }}/mkdocs-material
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true